In [11]:
import numpy as np
arr=np.array(45)
ar1=np.array([1,2,3])
arr2=np.array([[1,2],[3,4]])
arr3=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr4=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])

print(arr)
print(ar1)
print(arr2)
print(arr3)
print(arr4)
print(arr.ndim)
print(ar1.ndim)
print(arr2.ndim)
print(arr3.ndim)

45
[1 2 3]
[[1 2]
 [3 4]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
0
1
2
3


In [26]:
import numpy as np
arr=np.array(45)
arr1=np.array([1,2,3])
arr2=np.array([[1,2],[3,4]])
arr3=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr4=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
#indexing
print(ar1[0])
print(arr1[1]+arr1[2])
print(arr2[0,1])
print(arr2[1,0])
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a[1,4])
print(a[0,3])
print(arr3[0,1,1])
print(a[1,-1])
print(arr1[0:2])
print(a[0,:4])
print(a[-1,-1:-4:-1])
print(a[0:2,1:4])

1
5
2
3
10
4
4
10
[1 2]
[1 2 3 4]
[10  9  8]
[[2 3 4]
 [7 8 9]]


In [36]:
import numpy as np
arr=np.array(45)
arr1=np.array([1,2,3])
arr2=np.array([[1,2,3],[4,5,6]])
arr3=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
#indexing
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)
print(arr2[1,0])
a=np.array([[1,2,3,4,5,6,7,8,9,10,11,12]])
print(a.reshape(2,6))
print(a.reshape(3,4))
print(a.reshape(2,3,2))
print(a.reshape(3,2,-1))
print(arr2.reshape(-1))
for i in arr1:
    print(i)
for i in arr2:
    print(i)
for i in np.nditer(arr3):
    print(i)

(3,)
(2, 3)
(2, 2, 2)
4
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
[1 2 3 4 5 6]
1
2
3
[1 2 3]
[4 5 6]
1
2
3
4
5
6
7
8


In [42]:
#wap to using numpy to create 2*5 array ittrate threw evry scaler element of that array skiping by one element 
import numpy as a
a1=a.array([[1,2,3,4,5],[6,7,8,9,10]])
for i in np.nditer(a1[:,::2]):
    print(i)
    

1
3
5
6
8
10
